baseURL = 'https://derekstevens.net/'
languageCode = 'en-us'
title = 'DerekStevens.net'

theme = 'hugo-book'

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

googleAnalytics = 'G-9DDL9X80G8'  # Add your UA-XXXXXXXXX-X if using
disqusShortname = 'derekstevens'  # Add if using Disqus

disablePathToLower = true
disableKinds = ['taxonomy']
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Theme-specific params
[params]
  BookTheme = 'dark' # or 'light' or 'auto'
  BookToC = true # Shows table of contents
  BookLogo = ''  # Add 'logo.png' in /static/ if desired
  BookFavicon = 'favicon.png'  # Place in /static/
  BookSection = 'docs' # Section for 
  BookDateFormat = 'January 2, 2006'
  BookSearch = true # Enable flexsearch
  BookComments = true  # Enable if adding Disqus
  BookPortableLinks = true # Experimental: Better link handling
  BookServiceWorker = true  # Experimental: Offline support

# Git integration (for showing edit links and commit info)
enableGitInfo = true
[params]
  BookRepo = 'https://github.com/realderekstevens/derekstevens.net'  # Your repo URL
  BookEditPath = 'edit/main/content'  # Path to edit files
  BookLastChangeLink = 'https://github.com/yourusername/derekstevens.net/commit/{{ .GitInfo.Hash }}'
  BookEditLink = 'https://github.com/yourusername/derekstevens.net/edit/main/{{ .Path }}'
